Introduce PSR-4 autoloading
postindustria-tech/pipeline-php-core pull request #8
Opened 2023-10-11 14:28 UTC by lukareihl

2023-10-12 11:05 UTC, justadreamer requested changes
also if possible could we remove the newline character changes before committing in the file header comments - so it does not pollute the diff?

2023-10-12 11:05 UTC, justadreamer commented on examples/CustomFlowElement.php
>  include(__DIR__ . "/../vendor/autoload.php");
do we still need this include here?

2023-10-13 07:38 UTC, lukareihl commented on examples/CustomFlowElement.php
>  include(__DIR__ . "/../vendor/autoload.php");
Good catch, removed.

2023-10-13 13:26 UTC, justadreamer approved these changes

2023-10-13 13:26 UTC, justadreamer commented on examples/Pipeline.php
>  require(__DIR__ . "/../vendor/autoload.php");
perhaps this one can also be removed?

2023-10-16 10:54 UTC, merged